sudo: required
language: python
python:
  - 3.6
  - 3.7
  - 3.8

addons:
  firefox: "62.0.2"
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_install:
  # - sudo apt-get update
  # - sudo apt-get -y install firefox wget
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xvzf geckodriver-v0.26.0-linux64.tar.gz
  - sudo cp geckodriver /usr/local/bin/
  - sudo chmod a+x /usr/local/bin/geckodriver
  # - sudo apt-get -y install chromium-driver
  - python --version
  - pip install -U pip
# - pip install -U pytest
  - pip install nose
  - pip install codecov


install:
  - pip install -r requirements.txt
  - pip install .

script:
  - nosetests --with-coverage -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - coveralls

branches:
  only:
    - master
